<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1 (Python 3.6.7 on linux)" generated="20181214 11:15:32.693" rpa="false">
<suite id="s1" name="Test" source="/home/senseandserve/work/security-scorecard-online-store/rf_test/test">
<suite id="s1-s1" name="Gherkin Login" source="/home/senseandserve/work/security-scorecard-online-store/rf_test/test/gherkin_login.robot">
<test id="s1-s1-t1" name="Order Produt">
<kw name="Given browser is opened to home page" library="web_app_keywords">
<kw name="Start Virtual Display" library="XvfbRobot">
<doc>Starts virtual display which will be
 destroyed after test execution will be end</doc>
<arguments>
<arg>1920</arg>
<arg>1080</arg>
</arguments>
<msg timestamp="20181214 11:15:33.191" level="INFO">Using virtual display: '1920x1080x24'</msg>
<status status="PASS" starttime="20181214 11:15:33.191" endtime="20181214 11:15:33.294"></status>
</kw>
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the given ``url``.</doc>
<arguments>
<arg>${SERVER}</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20181214 11:15:33.295" level="INFO">Opening browser 'chrome' to base url 'https://security-scorecard-online-stor.herokuapp.com'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes screenshot of the current page and embeds it into log file.</doc>
<status status="FAIL" starttime="20181214 11:15:36.626" endtime="20181214 11:15:36.626"></status>
</kw>
<msg timestamp="20181214 11:15:36.626" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<status status="FAIL" starttime="20181214 11:15:33.294" endtime="20181214 11:15:36.628"></status>
</kw>
<status status="FAIL" starttime="20181214 11:15:33.189" endtime="20181214 11:15:36.629"></status>
</kw>
<status status="FAIL" starttime="20181214 11:15:33.188" endtime="20181214 11:15:36.631" critical="yes">Execution terminated by signal</status>
</test>
<test id="s1-s1-t2" name="Delete">
<tags>
<tag>robot:exit</tag>
</tags>
<status status="FAIL" starttime="20181214 11:15:36.637" endtime="20181214 11:15:36.642" critical="yes">Test execution stopped due to a fatal error.</status>
</test>
<kw name="Close Browser" library="SeleniumLibrary" type="teardown">
<doc>Closes the current browser.</doc>
<msg timestamp="20181214 11:15:36.647" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6a58&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
<msg timestamp="20181214 11:15:36.650" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6c88&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
<msg timestamp="20181214 11:15:36.653" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6d30&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
<status status="PASS" starttime="20181214 11:15:36.647" endtime="20181214 11:15:36.690"></status>
</kw>
<doc>Test suite as a demo task for Secure score card QA position
Prepare automated tests on UI level:
Test 1: Order Product
Step 1: add product A and B to a cart
Step 2: Remove A &amp;amp; add C
Step 3: Submit order for products A and C
Test 2: Delete order
Step 1: Query product on id
Step 2: Delete order</doc>
<status status="FAIL" starttime="20181214 11:15:32.716" endtime="20181214 11:15:36.690"></status>
</suite>
<status status="FAIL" starttime="20181214 11:15:32.694" endtime="20181214 11:15:36.701"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="2">Critical Tests</stat>
<stat pass="0" fail="2">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
<stat pass="0" fail="1">robot:exit</stat>
</tag>
<suite>
<stat pass="0" fail="2" id="s1" name="Test">Test</stat>
<stat pass="0" fail="2" id="s1-s1" name="Gherkin Login">Test.Gherkin Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20181214 11:15:36.626" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<msg timestamp="20181214 11:15:36.647" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6a58&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
<msg timestamp="20181214 11:15:36.650" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6c88&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
<msg timestamp="20181214 11:15:36.653" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7f0ef6cf6d30&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /session/fa4fa699de1a665fdc8c2b1ea7119c7c</msg>
</errors>
</robot>
